# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Formulate documentation
description: >- # this means to ignore newlines until "baseurl:"
  This site contains documentation for "formulate" - the forms library
  for the Department of Veterans Affairs.
baseurl: "/formulate" # the subpath of your site, e.g. /blog
url: "https://department-of-veterans-affairs.github.io/formulate" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs # This is specific to GitHub Pages
plugins:
  - jekyll-remote-theme
