name: Yarn publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
    
    - name: Install dependencies in react-components
      run: yarn install
    
    - name: Build package NPM package
      run: yarn build
    
    - name: Publish build artifacts to NPM
      run: npm publish --access public --tolerate-republish
      env:
        YARN_NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}